version: "3.8"

services:
  web:
    container_name: u1_web
    ports:
      - "8050:8050"
    build:
      context: .
    command: gunicorn u1django.wsgi:application --bind 0.0.0.0:8050 --workers=1 --timeout=60