name: CI/CD django
# test comment

on:
  push:
    branches:
      - main
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: django-deploy
          IMAGE_TAG: latest

        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_publish
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host deployment
            Hostname ${{ secrets.IP_ADDRESS }}
            User ec2-user
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
      - name: Create env file
        run: |
          echo BE_IMAGE="${{ secrets.IMAGE_URI }}/django-deploy:latest" >> .env
      - name: Pull image and deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          IMAGE_REMOTE: ${{ secrets.IMAGE_URI }}
          IMAGE_REMOTE_URI: ${{ secrets.IMAGE_URI }}/django-deploy
        run: |
          ssh -i ~/.ssh/dev.key -o StrictHostKeyChecking=no ec2-user@${{ secrets.IP_ADDRESS }} << 'ENDSSH'
            mkdir -p django_deploy
            aws configure set aws_access_key_id ${{secrets.AWS_ACCESS_KEY_ID}}; aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY}}; aws configure set default.region ${{ secrets.AWS_REGION }}
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.IMAGE_REMOTE }}
          ENDSSH
          scp -i ~/.ssh/dev.key -o StrictHostKeyChecking=no -r .env ec2-user@${{ secrets.IP_ADDRESS }}:./django_deploy
          scp -i ~/.ssh/dev.key -o StrictHostKeyChecking=no -r docker-compose-deploy.yml ec2-user@${{ secrets.IP_ADDRESS }}:./django_deploy
          ssh -i ~/.ssh/dev.key -o StrictHostKeyChecking=no ec2-user@${{ secrets.IP_ADDRESS }} << 'ENDSSH'
            cd django_deploy
            docker pull ${{ env.IMAGE_REMOTE_URI }}:latest
            docker-compose -f docker-compose-deploy.yml down
            docker-compose -f docker-compose-deploy.yml up -d
          ENDSSH
          

          
